name: Feature Request
description: Suggest an idea or enhancement for k3d-local
title: "[Feature] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I have checked the roadmap and planned features
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you're requesting
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem you're trying to solve or the use case this feature would enable
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution for this feature
      placeholder: What would you like to happen? How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: What other solutions have you considered? Are there existing workarounds?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the project does this feature relate to?
      options:
        - Cluster Management
        - Monitoring Stack
        - Configuration & Variables
        - Testing & Validation
        - Documentation
        - Developer Experience
        - CI/CD & Automation
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Important for my use case
        - Critical - Blocking my adoption/usage
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      options:
        - label: I would be willing to implement this feature and submit a PR
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, examples, or related information about the feature request
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Are there examples of this feature in other projects or tools?
      placeholder: Links to similar features in other tools, code examples, or mockups
    validations:
      required: false